#1
x1=int(input())
x2=int(input())
y1=int(input())
y2=int(input())
a=(x2-x1)
b=(y2-y1)
c=((a**2+b**2)**0,5)
print(c)

#2
a=int(input())
b=int(input())
c=int(input())
AC=a+c
BC=b+c
print(AC,BC,AC+BC)
#3
a=int(input())
b=int(input())
c=int(input())
k=0
AC=a+c
BC=b+c
if((c>=a)and(c<=b))or((c>=b)and(c<=a)):
    k=AC*BC
if(k==0):
    print("c ne pravilnoe")
print(k)
#4
x1=int(input())
y1=int(input())
x2=int(input())
y2=int(input())
x1=max(x1,x2)
y1=max(y1,y2)
x2=min(x1,x2)
y2=min(y1,y2)
a=x1-x2
b=y1-y2
P=(a+b)*2
S=a*b
print(P,S)
#5
x1=int(input())
x2=int(input())
x3=int(input())
y1=int(input())
y2=int(input())
y3=int(input())
a=((x1-x2)**2+(y1-y2)**2)**0,5
b=((x2-x3)**2+(y2-y3)**2)**0,5
c=((x3-x1)**2+(y3-y1)**2)**0,5
p=(a+b+c)/2
S=(p*(p-a)*(p-b)*(p-c))**0,5
print(S,p*2)
